name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag kakao-skill-server

    - name: Deploy Service
      run: ./deploy.sh

